# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Change the backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js

    - name: Start Backend
      run: npm run server &

    - name: Start Frontend
      run: npm start &

    - name: Install wait-on
      run: npm install -g wait-on

    - name: Wait for Frontend
      run: npx wait-on http://localhost:3000

    - name: Execute the UI tests
      run: npm run test
    
  deploy_be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.BACKEND_KEY }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
  
  deploy_fe:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.FRONTEND_KEY }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true    
